# Generated by Django 4.0 on 2021-12-23 11:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pingvi_app', '0002_alter_approach_options_alter_client_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='therapy_session',
            name='client',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='pingvi_app.client', verbose_name='Client'),
        ),
    ]
